language: php

php:
  - 7.3
#  - nightly

services:
  - postgres:11.2

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install

before_script:
  - psql -c 'create database testing;' -U postgres

script:
  - vendor/bin/ecs check --config=ecs.yml .
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry vendor/bin/php-coveralls -v
